# Generated by Django 4.2.5 on 2023-09-30 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("healthApp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="healthinformation",
            name="avatar",
            field=models.ImageField(
                blank=True, null=True, upload_to="medical_record_pic/"
            ),
        ),
    ]
